### ISSUE TITLE
eglot does not recognize the mode because it's called purs-mode instead of purescript-mode

### ISSUE THREAD

**Issue by jgarte** [PureFunctor/purs-mode#1]
Hi,

eglot does not recognize the mode because it's called purs-mode instead of purescript-mode:

https://github.com/joaotavora/eglot/blob/master/eglot.el#L203

Would it be ok to rename the part in the code that registers the mode to `purs-mode` to `purescript-mode`?

If so, I can submit a PR.

Does `lsp-mode` handle `purs-mode` automatically?

![image](https://user-images.githubusercontent.com/47760695/195483746-1ad5118c-add0-408c-9c84-37bfdaa295f9.png)

**Comment by purefunctor** [comment]
`lsp-mode` unfortunately only recognizes `purs-mode`, if I recall correctly. I think sending PRs upstream for both packages to recognize the same form would be ideal

**Comment by jgarte** [comment]
It looks like lsp-mode also recognizes `purescript-mode`:

https://github.com/emacs-lsp/lsp-mode/blob/b2dc84128fc6b2cd0460569bae6d0451856d2e0b/clients/lsp-purescript.el#L85

**Comment by purefunctor** [comment]
Ah, it could be that I'm manually patching this in my config or something

**Comment by purefunctor** [comment]
Fixed as of 16553383915cf453747a491715ed0427c107cc9e
